layout:
  qmk_keyboard: corne_rotated
  qmk_layout: LAYOUT_split_3x6_3
layers:
  QWERTY:
    - [null, "Q"                 , "W"                 , "E"                , "R"                , "T",   "Y", "U"                , "I"                , "O"                 , "P"                   , null]
    - [null, {t: "A", h: "LShft"}, {t: "S", h: "LCtrl"}, {t: "D", h: "LAlt"}, {t: "F", h: "LCmd"}, "G",   "H", {t: "J", h: "RCmd"}, {t: "K", h: "RAlt"}, {t: "L", h: "RCtrl"}, {t: ": ;", h: "RShft"}, null]
    - [null, {t: "Z", h: "("}    , "X"                 , "C"                , "V"                , "B",   "N", "M"                , "< ,"              , "> ."               , {t: "? /", h: ")"}    , null]
    #
    - [{t: "Esc", h: "FunCtl"}, {t: "Tab", h: "<FunCtl>"}, {t: "Space", h: "<NumNav>"},   {t: "Space", h: "<NumNav>"}, {t: "BSpc", h: "<FunCtl>"}, {t: "Ret", h: "NumNav"}]
  NUMNAV:
    - [null, "! 1"                 , "@ 2"                  , "# 3"                 , "$ 4"                   , "% 5" ,   "^ 6" , "& 7"                 , "* 8"               , "( 9"                   , ") 0"                  , null]
    - [null, {t: "` ~", h: "LShft"}, {t: "Home", h: "LCtrl"}, {t: "PgUp", h: "LAlt"}, {t: "PgDown", h: "LCmd"}, "End" ,   "Left", {t: "Down", h: "RCmd"}, {t: "Up", h: "RAlt"}, {t: "Right", h: "RCtrl"}, {t: "' \"", h: "RShft"}, null]
    - [null, "{ ["                 , null                   , null                  , null                    , "Caps",   "Del" , "- _"                 , "= +"               , "\\ |"                  , "} ]"                  , null]
    #
    - [{t: "Esc", h: "Qwerty"}, {t: "Tab", h: "<FunCtl>"}, "Space",   "Space", {t: "BSpc", h: "<FunCtl>"}, {t: "Ret", h: "FunCtl"}]
  FUNCTL:
    - [null, "F1"                   , "F2", "F3", "F4", "F5",                               "F6","F7", "F8", "F9", "F10", null]
    - [null, {t: "", h: "LShft"}, {t: "", h: "LCtrl"}, {t: "", h: "LAlt"}, {t: "", h: "LCmd"}, null,   null, {t: "", h: "RCmd"}, {t: "", h: "RAlt"},  {t: "F11", h: "RCtrl"}, {t: "F12", h: "RShft"}, null]
    - [null, "BT_1", "BT_2", "BT_3", "BT_4", "BT_5",                   "BT_CLR", "OUT_BLE", "OUT_USB", null, null, null]
    #
    - [{t: "Esc", h: "NumNav"}, "Tab", "Space",   "Space", "BSpc", {t: "Ret", h: "Qwerty"}]
